spring:
  application:
    name : spring-boot-trincheiras
  threads:
    virtual:
      enabled: true
logging:
  level:
    studies.wallace: debug
server:
  servlet:
    context-path: /
  error:
    include-stacktrace: on_param
  tomcat:
    threads:
      max: 20
